"""empty message

Revision ID: 112caca30f60
Revises: 4fd5329bb0ed
Create Date: 2023-04-27 09:31:03.515122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112caca30f60'
down_revision = '4fd5329bb0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedTrips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('savedTrips_city_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'city', ['city_id'], ['id'])
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedTrips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('savedTrips_city_fkey', 'city', ['city'], ['id'])
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###
